sudo: false

language: python

python:
  - 2.7
  - 3.5

env:
  - TOXENV=django18
  - TOXENV=django19
  - TOXENV=django110

matrix:
 include:
  - python: 3.5
    env: TOXENV=quality

cache:
    directories:
        - $HOME/.cache/pip

install:
  - pip install coveralls
  - pip install -r test_requirements.txt

script:
  - tox

after_success:
  - coveralls
