sudo: false
language: python
python:
  - "2.7"
cache:
    directories:
        - $HOME/.cache/pip
install:
  - pip install coveralls
  - python setup.py install
  - pip install -r test_requirements.txt
script:
  - coverage run -m nose
  - pep8 i18n
  - scripts/max_pylint_violations 20
after_success:
  - coveralls
branches:
    only:
      - master